language: php

php:
  - '7.2'

services:
  - mysql

cache:
  directories:
    - vendor

install:
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest

before_script: ~
script: ~
